.eslintrc.json, .vscode/settings.json, app.vue, assets/css/main.css, components/Countdown.vue, components/HoldingPage.vue, components/Socials.vue, eslint.config.js, nuxt.config.ts, package-lock.json, package.json, sentry.client.config.ts, sentry.server.config.ts, tailwind.config.js
This pull request includes several changes to improve code consistency, enhance accessibility, and update configurations. The changes span multiple files and focus on code formatting, accessibility improvements, and configuration updates.
* [`components/Countdown.vue`](diffhunk://#diff-11c516afc67293a67eb69b726bba8f36abb0fccbef246597a67c7f19247db258L63-R84): Added semicolons and updated formatting for consistency.
* [`components/HoldingPage.vue`](diffhunk://#diff-f2f32cdb73cd0ad2f5446533c47b4c44a6fd7551b2f183a063ecbb9048aeae41L8-R38): Added semicolons and updated formatting for consistency.
* [`components/Socials.vue`](diffhunk://#diff-229c6c635bedc167560a03c68e873a7c2d66447a4eae4993bf4aaf14fa689672L3-R29): Added semicolons and updated formatting for consistency.
* …
=> fix eslint and add meta tags

app.vue, assets/css/main.css, components/HeroBanner.vue, components/button.vue, pages/index.vue
This pull request includes several changes to improve the user interface and styling of the application. The most important changes involve the addition of new components and updates to existing styles.
* [`components/HeroBanner.vue`](diffhunk://#diff-f7561abdbd8b07c0e01990c282131c9d83bcefd9bab9383f28edda92f95bb765R1-R57): Added a new `HeroBanner` component with configurable properties for title, subtitle, images, and button details. This component enhances the visual appeal of the homepage.
* [`components/button.vue`](diffhunk://#diff-8b5691fc5a121d443b97bee02298354c3f7acccc8ae30591d4aba87168bbdc59R1-R23): Introduced a new `RosesButton` component to create styled buttons with customizable text and links. This component is used within the `HeroBanner` component.
* …
=> Hero banner

app.vue, components/SponsorsBanner.vue, components/TextImageSection.vue, components/button.vue, pages/index.vue
This pull request introduces several new components and modifies existing ones to enhance the user interface and layout of the application. The most important changes include adding a new `SponsorsBanner` component, creating a reusable `TextImageSection` component, and updating the `index.vue` page to incorporate these new components. Should close this task: https://linear.app/yorksu/issue/ROS-65/homepage
* [`components/SponsorsBanner.vue`](diffhunk://#diff-a0457fe5eb2dd5aadd471837910d16984b7f9cebaf6b96e8a6865340a6336d7aR1-R35): Added a new component to display sponsor logos with a supporting layout and styles.
* [`components/TextImageSection.vue`](diffhunk://#diff-f11e2507ef8b31f819c397d474f79ec12847f916582a0302d343ed41eac909b5R1-R59): Introduced a new reusable component that combines …
=> Sponsor banner and text/image sections

pages/activities.vue, tailwind.config.js
Created a page which lists all of the activities and links through to their specific pages.
=> Activities Page

components/HoldingPage.vue, pages/activities/[id].vue, pages/activities/index.vue, pages/fixtures/index.vue, pages/index/index.vue
Fixtures and started work on activities/[id], and a change to the file/folder structure to use folders with index.vue.
=> Fixtures, file structure

components/footer.vue
This pull request includes a change to the `components/footer.vue` file to enhance the footer section with additional information and visual elements.
Enhancements to the footer section:
* Added a new `div` container with a `flex-col` class to organize elements in a column layout.
* Included an image from the Green Web Foundation to indicate that the website runs on green hosting.
=> Add green hosting link

pages/index.vue
=> Reduced the text content on the homepage

app.vue, components/CtaTiles.vue, components/footer.vue, components/navbar.vue, nuxt.config.ts, package-lock.json, pages/activities/[id].vue, pages/activities/index.vue, pages/contributors/index.vue, pages/fixtures/index.vue, pages/index.vue
Sorry, this is a 241 PR with a couple of other things added in!
This pull request includes several updates to improve the user interface and enhance the SEO of the website. The most important changes include adding meta tags for better SEO, modifying links and attributes in various components, and updating the navigation bar's link visibility.
SEO Enhancements:
* `pages/activities/[id].vue`, `pages/activities/index.vue`, `pages/contributors/index.vue`, `pages/fixtures/index.vue`, `pages/index.vue`: Added `useHead` to set the page titles and meta descriptions for better SEO. ([pages/activities/[id].vueR63-R65](diffhunk://#diff-4a6cb4a42737ef40f1b9fa722aae786b7b8b596265ed6b764d7d8503553d2d26R63-R65), [[1]](diffhunk://#diff-80558c632f5c1457f9fa6596b67fa9fb38815a6be46b081c3e53e501c17c3254R63-R …
=> York SU Logo on safari and SEO

components/HistoricFixtureTile.vue, package-lock.json, package.json
Ooopsie made a woopsie
This pull request includes changes to a Vue component and an update to a package dependency in `package.json`.
Updates to Vue component:
* [`components/HistoricFixtureTile.vue`](diffhunk://#diff-a7a27de1ec3745b377c22ee2cb804f5f2eee0e25c021908fcae4e05fc699a1a2L27-R35): Corrected the score formatting for the teams by swapping the indices used in the `formatScore` function.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L33-R33): Updated the `eslint-plugin-vue` dependency from version `^9.28.0` to `^10.0.0`.
=> Switch Scores

pages/activities/[id].vue
This pull request includes changes to the `pages/activities/[id].vue` file to improve the handling and display of sports data. The most important changes include replacing the use of `fixtures[0]?.sport` with a new `sport` object, updating the template to use this new object, and modifying the data fetching logic to retrieve the sport data separately.
Improvements to data handling and display:
* Replaced `fixtures[0]?.sport` with `sport` for better data handling and clarity in the template. (`pages/activities/[id].vue`) ([pages/activities/[id].vueR1-R13](diffhunk://#diff-4a6cb4a42737ef40f1b9fa722aae786b7b8b596265ed6b764d7d8503553d2d26R1-R13))
* Added a new `sport` object to the component's data properties. (`pages/activities/[id].vue`) …
=> update to use new endpoint

components/CtaTiles.vue, components/Socials.vue, components/SponsorsBanner.vue, components/TextImageSection.vue, components/button.vue, package-lock.json, pages/get-involved/index.vue, pages/index.vue
This pull request includes several updates to multiple Vue components to enhance the functionality and improve the user experience. The most important changes include adding `href` attributes to anchor tags, introducing `target` attributes for links, and modifying sponsor links to open in new tabs with tracking parameters.
* [`components/CtaTiles.vue`](diffhunk://#diff-9060a3c4c017c0f43fef18753c09c767bc468fd7ebeb53b3638622802f38c745L26-R29): Added `href` attributes to anchor tags to ensure they link to the correct pages. [[1]](diffhunk://#diff-9060a3c4c017c0f43fef18753c09c767bc468fd7ebeb53b3638622802f38c745L26-R29) [[2]](diffhunk://#diff-9060a3c4c017c0f43fef18753c09c767bc468fd7ebeb53b3638622802f38c745L39-R45) [[3]](diffhunk://#diff-9060a3c4c017c0f43fef18753c09c767bc468fd7ebeb53b3638622802f …
=> update and add sponsors

pages/get-involved/index.vue
=> Added updated "Get Involved" content

pages/about/index.vue
=> Added updated "About Us" content

components/HeroBanner.vue, pages/index.vue
=> Updated Homepage Herobanner

nuxt.config.ts
This pull request introduces a new security configuration in the `nuxt.config.ts` file to enhance the application's security by implementing a comprehensive Content Security Policy (CSP) and Subresource Integrity (SRI).
Security enhancements:
* Added a `security` section to the Nuxt configuration to define CSP headers, including `script-src`, `style-src`, `base-uri`, `img-src`, `font-src`, `object-src`, `script-src-attr`, and `upgrade-insecure-requests`. This helps mitigate various web vulnerabilities by controlling the sources from which content can be loaded.
* Enabled Subresource Integrity (SRI) to ensure that external resources have not been tampered with, enhancing the security of the application.
=> add report/csp

assets/css/main.css, components/footer.vue, components/navbar.vue, pages/about/index.vue, pages/activities/[id].vue, pages/contributors/index.vue, pages/fixtures/index.vue, pages/food-and-drink/index.vue, pages/get-involved/index.vue, pages/index.vue, pages/terms-and-conditions/index.vue
This pull request includes several updates to the website's content and structure, mainly focusing on enhancing the layout and updating links. The most important changes include adding a new page for food and drink, updating the `Food & Drink` link across multiple components, and improving the layout by adding a `body` class wrapper to several pages.
* Added a new `Food & Drink` page with a hero banner and content section. (`pages/food-and-drink/index.vue`)
* Updated the `Food & Drink` link in the `footer.vue` and `navbar.vue` components to point to the new page. (`components/footer.vue`) [[1]](diffhunk://#diff-45a0dde9637f50ff1e2e69f413a3828336c2668bff9b22ee047d1ce21c36170cL21-R21) (`components/navbar.vue`) [[2]](diffhunk://#diff-6b7e7b8175dd6130983dc472b3f3ff12268706e1a304a05fb8c286020e8 …
=> Container tweak and latest content

pages/activities/[id].vue, pages/fixtures/index.vue
=> Removed container styling from fixtures

components/FixtureSearch.vue, components/TextImageSection.vue, components/addToCalendar.vue
This pull request includes several accessibility improvements to various components in the project. The main changes involve adding aria labels, conditional rendering of elements, and improving the semantic structure of the HTML.
Accessibility improvements:
* [`components/FixtureSearch.vue`](diffhunk://#diff-6d7774c3c34fa57bf2fb1a208ea98052c0906155d75dcfeda102f0a5eb05d547R4-R6): Added a label for the search input to improve accessibility for screen readers.
* [`components/TextImageSection.vue`](diffhunk://#diff-f11e2507ef8b31f819c397d474f79ec12847f916582a0302d343ed41eac909b5L14-R15): Added conditional rendering for `title` and `subTitle` to ensure that empty elements are not rendered.
* [`components/addToCalendar.vue`](diffhunk://#diff-80cbd610117870688c01a71c9db328b2eda30b23ed115ba8f3c589 …
=> Accessibility fixes

pages/about/index.vue, pages/food-and-drink/index.vue, pages/get-involved/index.vue
=> Content updates

assets/css/main.css
=> Allow score tile to expand for large scores

components/footer.vue
=> Added SCAN link to footer

components/CtaTiles.vue, components/HoldingPage.vue, components/SponsorsBanner.vue, components/footer.vue, components/navbar.vue, pages/about/index.vue, pages/contributors/index.vue, pages/food-and-drink/index.vue, pages/get-involved/index.vue, pages/index.vue
Updated content with new content and tracking links.
=> Updated content

components/RosesMap.vue, package-lock.json
This pull request introduces several changes to the `components/RosesMap.vue` file to add and manage a new layer of venues on the map. The changes include adding new data properties, configuring a new data source, and handling user interactions with the new venues layer.
Key changes include:
* Added `venues` and `formattedVenues` arrays to the component's data properties to store venue information and their formatted versions.
* Fetched venue data from an API and populated the `formattedVenues` array with the fetched data.
* Added a new GeoJSON source for venues and configured a new map layer to display these venues as circles. [[1]](diffhunk://#diff-09883069380466b34c4e89bd9df2616a3d0c9ab4823c595751bccc41e2882a9eR64-R71) [[2]](diffhunk://#diff-09883069380466b34c4e89bd9df2616a3d0c9ab4823c5 …
=> Food and Drink on Map

package-lock.json, pages/about/index.vue
* update content
* npm update
* comment out final line
> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.  
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.  
> If the UI is being changed, please provide screenshots.
=> update content (#184)

components/footer.vue, components/navbar.vue
=> Unhide shop

components/RosesMap.vue
=> Added facilities to venue feature

components/LiveReporting.vue
=> Fixed live mobile view

assets/css/main.css, components/carousel.vue, nuxt.config.ts, pages/activities/[id].vue
=> Photo Gallery

components/LiveReporting.vue
Added an all tab to live reporting, and filters for blogs, photos, and score updates.
=> Added score updates, and photo updates

components/LiveReporting.vue
=> Added pagination to scores

components/LiveReporting.vue, components/LiveScore.vue, pages/live/index.vue
This pull request includes updates to the `LiveReporting`, `LiveScore`, and `live/index` components to improve layout flexibility, modify visuals, and introduce new features. Key changes include enhancing layout responsiveness, temporarily disabling a section, updating the hero banner, and adding a new `CtaTiles` component.
* Updated `LiveReporting.vue` to improve layout flexibility by adding `flex` and `gap` classes for better alignment and spacing in stream buttons.
* Added `min-h-2` and `min-w-2` to elements in `LiveScore.vue` to ensure minimum dimensions for better visual consistency. [[1]](diffhunk://#diff-bde034c430828cc758d0e3d2e1d044267f81cc3aaaf144b447d3fe27d41e9602L19-R26) [[2]](diffhunk://#diff-bde034c430828cc758d0e3d2e1d044267f81cc3aaaf144b447d3fe27d41e9602L53-R59)
* Updated …
=> Tweaks to live page

components/CtaTiles.vue, components/HeroBanner.vue, components/SponsorsBanner.vue, components/carousel.vue, error.vue, pages/about/index.vue, pages/activities/[id].vue, pages/contributors/index.vue, pages/fixtures/index.vue, pages/food-and-drink/index.vue, pages/get-involved/index.vue, pages/index.vue, pages/live/index.vue, pages/map/index.vue, pages/terms-and-conditions/index.vue
This pull request introduces consistent responsive spacing adjustments across multiple Vue components and pages. The changes primarily involve modifying padding (`py` and `pb` classes) to include responsive behavior, ensuring better layout adaptability on smaller screens. Below is a summary of the most important changes grouped by theme:
* Updated the `py` classes to use `py-14 md:py-28` for vertical padding in various components and pages, such as `CtaTiles.vue`, `SponsorsBanner.vue`, and `HeroBanner.vue`, to improve responsiveness. [[1]](diffhunk://#diff-9060a3c4c017c0f43fef18753c09c767bc468fd7ebeb53b3638622802f38c745L4-R4) [[2]](diffhunk://#diff-a0457fe5eb2dd5aadd471837910d16984b7f9cebaf6b96e8a6865340a6336d7aL4-R4) [[3]](diffhunk://#diff-f7561abdbd8b07c0e01990c282131c9d83bcefd9bab9383f2 …
=> Updating spacing on mobile

components/CtaTiles.vue, components/DayFilters.vue, components/FixtureTile.vue, components/HeroBanner.vue, components/HoldingPage.vue, components/LiveReporting.vue, components/LiveScore.vue, components/OgImage/RosesOgTemplate.vue, components/SponsorsBanner.vue, components/TextImageSection.vue, components/addToCalendarModal.vue, components/carousel.vue, components/footer.vue, components/navbar.vue, error.vue, nuxt.config.ts, package-lock.json, package.json, pages/about/index.vue, pages/activities/[id].vue, pages/contributors/index.vue, pages/fixtures/index.vue, pages/food-and-drink/index.vue, pages/get-involved/index.vue, pages/home/index.vue, pages/index.vue, pages/live/index.vue, pages/map/index.vue, pages/terms-and-conditions/index.vue
=> Boat races - v1.4

components/LiveReporting.vue
=> Increased radio iframe height

pages/about/index.vue
=> Added button to sustainability
