- assets/css/main.css
- components/Countdown.vue
- components/CtaTiles.vue
- components/HeroBanner.vue
- pages/index.vue
- tailwind.config.js
This pull request includes several changes to enhance the visual design and functionality of the countdown and call-to-action (CTA) components on the website. The changes involve updates to CSS styles, Vue components, and the main index page. This also closes: https://linear.app/yorksu/issue/ROS-67/countdown
* [`assets/css/main.css`](diffhunk://#diff-b15932692c619f9a334ecb156ac167557c3af214a8a3df8990c09232ac8a5baaL15-R22): Updated the `countdown-text` class to use a larger font size and a new color. Removed the italic style from the `.xcond` class.
* [`components/HeroBanner.vue`](diffhunk://#diff-f7561abdbd8b07c0e01990c282131c9d83bcefd9bab9383f28edda92f95bb765L9-R9): Added italic styling to the `title` in the hero banner to improve visual emphasis.
* …
> CTA tiles and Countdown

- assets/css/main.css
- components/DayFilters.vue
- components/FixtureSearch.vue
- components/FixtureTile.vue
- components/HeroBanner.vue
- components/button.vue
- pages/fixtures.vue
This PR includes the creation of the fixtures page, with the fixtures tile component, the day filters ( closing https://linear.app/yorksu/issue/ROS-73/day-filters-ui ), and the search box. These are purely UI features at the moment, and the functionality will be added once the backend is ready.
> Fixtures, fixture tile, day filters, and search box

- components/DayFilters.vue
- components/FixtureSearch.vue
- components/FixtureTile.vue
- components/LoadingFixtureTile.vue
- pages/fixtures/index.vue
This pull request includes significant updates to the `DayFilters.vue`, `FixtureTile.vue`, and `LoadingFixtureTile.vue` components, as well as modifications to the `fixtures` page. The changes focus on enhancing the user interface and improving the functionality of selecting and displaying fixtures based on days.
Key changes include:
* [`components/DayFilters.vue`](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0L4-R43): Replaced `RosesButton` components with custom `<button>` elements that dynamically update their styles based on the selected day and emit the `selectDay` event. Added methods to handle day selection and set the default day based on the current date. [[1]](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0L4-R4 …
> Initial work on day filters and loading state

- components/DayFilters.vue
- components/FixtureSearch.vue
- pages/fixtures/index.vue
This pull request includes changes to improve the search and filter functionalities in the fixtures component. The most important changes include adding conditions to handle empty search terms and selected days, and introducing references to manage search input values.
Improvements to search and filter logic:
* [`components/DayFilters.vue`](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0L88-R90): Modified the `searchTerm` watcher to call `setDefaultDay` only when both `searchTerm` is empty and `selectedDay` is null. Additionally, it now sets `selectedDay` to null only when `searchTerm` is not empty.
Enhancements to search input management:
* [`components/FixtureSearch.vue`](diffhunk://#diff-6d7774c3c34fa57bf2fb1a208ea98052c0906155d75dcfeda102f0a5eb05d547R6 …
> Clear search on day change

- components/DayFilters.vue
- pages/fixtures/index.vue
This pull request includes changes to the `components/DayFilters.vue` and `pages/fixtures/index.vue` files to enhance the display and organization of fixture data. The most important changes include adding names to day filters, grouping fixtures by date, and importing necessary utilities.
Enhancements to day filters:
* [`components/DayFilters.vue`](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0R69-R84): Added `name` properties to `before`, `friday`, `saturday`, and `sunday` filters.
Improvements to fixture display:
* [`pages/fixtures/index.vue`](diffhunk://#diff-b5f58aadf9924f3343cc9001c00a1f68d29f03ba5a8c0f678293804170d03abdR13-R27): Added a `v-for` loop to display grouped fixtures by date, including a date header for each group.
Code organization and …
> Separate out "Before" and search by date

- assets/css/main.css
- components/FixtureTile.vue
- components/HistoricFixtureTile.vue
- pages/activities/[id].vue
- pages/fixtures/index.vue
This pull request includes several changes to the fixture components and pages to improve the display and functionality of the fixtures and historic fixtures. The most important changes include updating the `FixtureTile` component, adding a new `HistoricFixtureTile` component, and modifying the `activities` page to display fixtures and historic fixtures more effectively.
* [`components/FixtureTile.vue`](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL2-R2): Changed the wrapper element from an `<a>` tag to a `<div>` tag to avoid issues with nested interactive content. [[1]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL2-R2) [[2]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL64-R61)
* …
> activity/[id] page with rules, fixtures, and historic fixtures

- components/footer.vue
This pull request includes changes to the `components/footer.vue` file to update and clean up the list of links displayed in the footer. The most important changes include updating the URLs for the "Fixtures," "Get Involved," and "About" links, and commenting out several unused or outdated links.
Updates to footer links:
* Updated the "Fixtures" link to point to `/fixtures` instead of being commented out.
* Updated the "Get Involved" link to point to `/get-involved` instead of being a plain text link.
* Updated the "About" link to point to `/about` instead of being a plain text link.
Clean-up of unused links:
* Commented out the "Food & Drink" link and the link to the shop on `yorksu.org`.
* Commented out the "Map" link.
> remove link to shop

- components/footer.vue
- pages/about/index.vue
- pages/activities/[id].vue
- pages/contributors/index.vue
- pages/get-involved/index.vue
- pages/terms-and-conditions/index.vue
This pull request includes several changes to the `Roses Live` website, focusing on adding a new page for terms and conditions, as well as setting the page titles dynamically for various pages.
* Added a new `Terms and Conditions` page with comprehensive content, including sections on Disclaimer, Accessibility, Copyright, and Cookies (`pages/terms-and-conditions/index.vue`).
* Set the page title dynamically for the `About` page (`pages/about/index.vue`).
* Set the page title dynamically for the `Get Involved` page (`pages/get-involved/index.vue`).
* Set the page title dynamically for the `Activities` page, replacing the previous static title (`pages/activities/[id].vue`). ([pages/activities/[id].vueR107-L113](diffhunk://#diff-4a6cb4a42737ef40f1b9fa722aae786b7b8b596265ed6b764d7d8503553d2d26 …
> Add terms and conditions and meta tags for new pages

- components/footer.vue
Resolves #144 
Changes YSTV to go to their YouTube channel, as well as adding Bailrigg FM and LA1TV.
I've also moved the Contact Details section to the first column, to make the two more even in height again
> Update media links in footer (#144)

- components/CtaTiles.vue
This pull request includes updates to the image sources in the `CtaTiles.vue` component to correct the displayed images for various tiles.
Changes to `components/CtaTiles.vue`:
* Updated the image source for the "Fixtures" tile to `Shop_Tile.png`.
* Updated the image source for the "Get Involved" tile to `Food_Drink_Tile.png`.
* Updated the image source for the "Food & Drink" tile to `Get_Involved_Tile.png`.
* Updated the image source for the "Shop" tile to `Fixtures_Tile.png`.
> swap images on tiles

- components/FixtureTile.vue
This pull request includes changes to the `components/FixtureTile.vue` file to improve the display and handling of fixture location names. The main change is the introduction of a new computed property to format location names, which is then used throughout the component.
Changes to fixture location handling:
* Added a new computed property `locationName` to format the fixture location name, including the parent location if available.
* Updated the template to use the new `locationName` computed property instead of directly accessing `fixture.location.name`. [[1]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL16-R16) [[2]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL60-R60) …
> Add parent location

- components/DayFilters.vue
- components/FixtureTile.vue
- components/RosesMap.vue
- components/addToCalendar.vue
- pages/fixtures/index.vue
This pull request includes several changes to enhance the functionality and user experience of the application. The changes primarily focus on adding location-based filtering and improving the layout and styling of various components.
* [`components/DayFilters.vue`](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0R73): Added `locationId` data property and updated the `mounted` method to handle location-based filtering by setting `selectedDay` to null if a location is provided in the query parameters. [[1]](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0R73) [[2]](diffhunk://#diff-91e1229dc5dfe79ac8157ae606c28aaaeff084f1af380cbea58285b8c619a7b0R107-R113)
* [`components/RosesMap.vue`](diffhunk://#diff-09883069380466b34c4e89bd …
> View fixtures from locations and vice versa

- components/LiveScore.vue
- pages/live/index.vue
This pull request introduces a new "Roses Live" page that displays live scores for the York vs. Lancaster competition. The most important changes include the creation of a `LiveScore` component to handle the score display and the addition of a new page that integrates this component with a hero banner.
* **Addition of `pages/live/index.vue`:** A new page has been created to serve as the "Roses Live" page. It includes a hero banner with a title and image, and integrates the `LiveScore` component to display live competition scores.
* **Creation of `LiveScore` Component (`components/LiveScore.vue`):** A new component has been added to display live scores for York and Lancaster. It includes:
- Dynamic bar and text visualizations for the scores.
- A method (`getPoints`) to fetch live score …
> Roses live score component

- components/LiveReporting.vue
- nuxt.config.ts
This pull request introduces support for distinguishing between TV and radio coverage in the `LiveReporting` component. It adds a new `coverage` property to the `activeStream` object, updates the conditional rendering logic to handle different coverage types, and ensures the necessary CSP (Content Security Policy) adjustments for embedding radio streams.
* Added a `coverage` property to the `activeStream` object to differentiate between TV and radio coverage. (`components/LiveReporting.vue`, [[1]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7R647) [[2]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7R657)
* Updated the conditional rendering logic to display TV coverage (`TVCoverage`) or radio coverage (`RadioCoverage`) …
> Added radio streams to live streams

- components/LiveReporting.vue
- pages/live/index.vue
This pull request introduces enhancements to the live reporting functionality and updates the user interface for the live page. The most significant changes include adding support for "main streams" in the live reporting component, refactoring video ID extraction logic into a reusable method, and adding a new button to the live page hero component.
* [`components/LiveReporting.vue`](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7R586): Introduced a new `mainStreams` property to handle a separate set of streams fetched from a different API endpoint. Combined `mainStreams` and `streams` to ensure `mainStreams` appear first in the final streams array. [[1]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7R586) …
> Added main streams, and fixtures button

- components/LiveReporting.vue
- components/navbar.vue
- pages/home/index.vue
- pages/index.vue
This pull request introduces multiple updates to the `Roses Live` project, focusing on API updates, navigation improvements, and significant changes to the homepage layout and content. The changes include updating API endpoints, modifying navigation links, and restructuring the homepage to enhance user experience and highlight live reporting and scores.
* Updated API endpoints in `components/LiveReporting.vue` to use production URLs instead of staging URLs for fetching fixture results. [[1]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7L707-R707) [[2]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7L729-R729)
* Changed the "Roses Live" navigation link in `components/navbar.vue` to point to `/live` instead of `/`.
* …
> Changed home page to live page

- components/FixtureTile.vue
This pull request refines the `FixtureTile` component by improving the layout and responsiveness, adding new UI elements for match outcomes, and ensuring better alignment across different screen sizes. The changes enhance the user experience by making the component more intuitive and visually appealing.
* Adjusted the `div` class attributes to improve alignment and spacing, such as adding `items-center` and `items-start` for better vertical alignment across screen sizes. (`[[1]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL16-R16)`, `[[2]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dR29-R64)`, `[[3]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dL68-R109)`)
* Introduced new …
> Clearer fixture winner & fixture tile UI tweaks

- components/LiveReporting.vue
It's now POINT(S) instead of point(s)
> add points for results

- components/LiveReporting.vue
This pull request updates the `LiveReporting.vue` component to improve the handling of conditional rendering for match outcomes. The changes ensure that the "Draw" outcome is properly displayed and fix the logic for rendering outcomes when multiple conditions are present.
* Updated `v-if` to `v-else-if` for the "Lancaster Win" condition to ensure proper evaluation of mutually exclusive outcomes. (`[[1]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7L286-R296)`, `[[2]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7L364-R380)`)
* Added a new `v-else-if` block to handle the "Draw" outcome for both `coverage.teams` and `score.teams`, ensuring it is displayed when applicable. …
> Added draw to results/coverage

- components/RosesMap.vue
- components/navbar.vue
- pages/food-and-drink/index.vue
This pull request introduces enhancements to the user experience by improving navigation and layout across multiple components. Key changes include adding smooth scrolling to a map component, improving the visibility of the mobile menu, and enhancing the layout and functionality of buttons on the "Food and Drink" page.
* [`components/RosesMap.vue`](diffhunk://#diff-09883069380466b34c4e89bd9df2616a3d0c9ab4823c595751bccc41e2882a9eR165-R182): Implemented smooth scrolling to the map container when a location is selected by ID, ensuring a better user experience for navigating the map. Also added support for locating venues in addition to locations and child locations.
* [`components/navbar.vue`](diffhunk://#diff-6b7e7b8175dd6130983dc472b3f3ff12268706e1a304a05fb8c286020e81f56aL48-R48): Added a …
> View venue locations on map, scroll into view, z-index fix

- components/LiveReporting.vue
This pull request refactors the `LiveReporting.vue` component to improve the organization of streams by categorizing them into `Main Streams`, `Video Streams`, and `Radio Streams`. It also simplifies the logic for setting the active stream and updates the UI to reflect these changes.
* Added separate sections in the UI to display `Main Streams`, `Video Streams`, and `Radio Streams`, each with its own heading and buttons for selection. [[1]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7R12-R16) [[2]](diffhunk://#diff-319fdf620485b8ca6fccff5cde8cb651f9fb4a7decd7cd2de091d8f786fed3d7L29-R90)
* Introduced new arrays (`video` and `radio`) to categorize streams based on their coverage type (`TVCoverage` for video and `RadioCoverage` for radio).
* Updated logic …
> Separated streams by type

- assets/css/main.css
- components/RosesMap.vue
- package-lock.json
- package.json
This pull request introduces a Vue-Select dropdown to the `RosesMap` component, allowing users to search and select locations. It also includes styling and functionality changes to support this feature. The most important changes are grouped into the following themes:
* Added `vue-select` as a dependency in `package.json` to enable the use of Vue-Select components.
* Imported `vue-select` in `RosesMap.vue` and registered it as a component. Added a Vue-Select dropdown in the template to allow users to search and select locations. [[1]](diffhunk://#diff-09883069380466b34c4e89bd9df2616a3d0c9ab4823c595751bccc41e2882a9eR2-R20) [[2]](diffhunk://#diff-09883069380466b34c4e89bd9df2616a3d0c9ab4823c595751bccc41e2882a9eR33-R40)
* Updated `main.css` to include Vue-Select styles by importing …
> Added search by location to map

- components/FixtureTile.vue
- components/LiveReportingResultTile.vue
This pull request introduces changes to handle and display "Forfeit" outcomes for the York and Lancaster teams in the `FixtureTile` and `LiveReportingResultTile` components. The updates ensure that forfeits are visually distinct and consistent with existing styles for other outcomes like "Draw."
* Added conditional blocks to check if York or Lancaster has a "Forfeit" outcome and display corresponding messages ("YORK FORFEIT" or "LANCASTER FORFEIT") with appropriate styling. These changes were applied in three different sections of the file to cover all relevant scenarios. [[1]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dR50-R63) [[2]](diffhunk://#diff-e60346bcf3c45a2565314d0c12cab591b7680f88e7339cc594feb88731c9b27dR127-R140) …
> Added forfeiting logic

- components/LiveReporting.vue
Labels the main streams with either (TV) or (Radio), since they're sharing a fixture and currently it's not clear which is which
> feat: distinguish between radio and tv main streams
